### ISSUE TITLE
Block theses types of ads

### ISSUE THREAD

**Issue by bensmithgb53** [MarcellPerger1/adblock-bookmarklet#31]
Could you get this to block ads where it opens new taps if I click somewhere on a website as it opens new virus links. Here is an example Website.  If I click anywhere on website is opens new website by itself. Could you get JavaScript to run evey 5 secounds 

https://bizzstreams2u.online/

**Comment by MarcellPerger1** [comment]
See https://github.com/MarcellPerger1/adblock-bookmarklet/issues/46#issuecomment-2176959800

**Comment by bensmithgb53** [comment]
Still opens new taps and doesn't blocks
